# Copyright 2019 Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0

AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31

Parameters:
  MediaInsightsEnginePython38Layer:
    Type: String
    Description: "ARN of the MIE Lambda layer (MediaInsightsEnginePython38Layer output of the main MIE CloudFormation stack)"
  WorkflowCustomResourceArn:
    Type: String
    Description: "ARN of the MIE custom resource (WorkflowCustomResourceArn output of the main MIE CloudFormation stack)"
  WorkflowEndpoint:
    Type: "String"
    Description: "Workflow endpoint (APIHandlerName output of the MIE Workflow CloudFormation nested stack)"
  DataplaneEndpoint:
    Type: "String"
    Description: "Dataplane endpoint (APIHandlerName output of the MIE Dataplane CloudFormation nested stack)"
  DataplaneBucket:
    Type: "String"
    Description: "Bucket for the dataplane (DataplaneBucket output of the main MIE CloudFormation stack)"

Globals:
  Function:
    Runtime: python3.8
    Handler: app.lambda_handler
    Timeout: 300
    MemorySize: 1024
    Layers:
      - !Ref MediaInsightsEnginePython38Layer
    Environment:
      Variables:
        DATAPLANE_BUCKET: !Ref DataplaneBucket
        DataplaneEndpoint: !Ref DataplaneEndpoint

Resources:
  #############
  # IAM Roles #
  #############
  MediaConvertS3Role:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - mediaconvert.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      Policies:
        - PolicyName: MediaConvertS3RolePolicy
          PolicyDocument:
            Statement:
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:PutObject
                Resource:
                  - !Sub "arn:aws:s3:::${DataplaneBucket}/*"
  LambdaMediaConvertRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
        - arn:aws:iam::aws:policy/AmazonS3ReadOnlyAccess
      Policies:
        - PolicyName: LambdaMediaConvertRolePolicy
          PolicyDocument:
            Statement:
              - Effect: Allow
                Action:
                  - mediaconvert:GetJob
                  - mediaconvert:ListJobs
                  - mediaconvert:DescribeEndpoints
                  - mediaconvert:CreateJob
                Resource:
                  - "*"
              - Effect: Allow
                Action:
                  - iam:PassRole
                Resource:
                  - !GetAtt MediaConvertS3Role.Arn
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:PutObject
                Resource:
                  - !Sub "arn:aws:s3:::${DataplaneBucket}/*"
              - Effect: Allow
                Action:
                  - lambda:InvokeFunction
                Resource:
                  - !Sub "arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:${DataplaneEndpoint}*"
  LambdaDataplaneRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
        - arn:aws:iam::aws:policy/AmazonS3ReadOnlyAccess
      Policies:
        - PolicyName: LambdaDataplaneRolePolicy
          PolicyDocument:
            Statement:
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:PutObject
                Resource:
                  - !Sub "arn:aws:s3:::${DataplaneBucket}/*"
              - Effect: Allow
                Action:
                  - lambda:InvokeFunction
                Resource:
                  - !Sub "arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:${DataplaneEndpoint}*"
  LambdaWorkflowRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
        - arn:aws:iam::aws:policy/AmazonS3ReadOnlyAccess
      Policies:
        - PolicyName: LambdaWorkflowRolePolicy
          PolicyDocument:
            Statement:
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:PutObject
                Resource:
                  - !Sub "arn:aws:s3:::${DataplaneBucket}/*"
              - Effect: Allow
                Action:
                  - lambda:InvokeFunction
                Resource:
                  - !Sub "arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:${WorkflowEndpoint}*"
  StateMachineExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - states.amazonaws.com
            Action:
              - sts:AssumeRole
      Policies:
        - PolicyName: StateMachineExecutionRolePolicy
          PolicyDocument:
            Statement:
              - Effect: Allow
                Action:
                  - lambda:InvokeFunction
                Resource:
                  - "arn:aws:lambda:*:*:function:*"

  ###################################
  # Input bucket and Lambda funcion #
  ###################################
  InputBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: 'AES256'
  InputBucketPolicy: 
    Type: AWS::S3::BucketPolicy
    Properties: 
      Bucket: !Ref InputBucket
      PolicyDocument: 
        Statement: 
          - Effect: Deny
            Action: 
              - s3:*
            Resource: 
              - !Sub "arn:aws:s3:::${InputBucket}/*"
              - !Sub "arn:aws:s3:::${InputBucket}"
            Principal: "*"
            Condition: 
              Bool: 
                aws:SecureTransport: false
  InputFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: input/
      Role: !GetAtt LambdaWorkflowRole.Arn
      Environment:
        Variables:
          WORKFLOW_NAME: "SmartAdBreaksWorkflow"
          WorkflowEndpoint: !Ref WorkflowEndpoint
      Events:
        S3Bucket:
          Type: S3
          Properties:
            Bucket: !Ref InputBucket
            Events: s3:ObjectCreated:*

  ########################################
  # Lambda functions of custom operators #
  ########################################
  VideoTranscodingStartFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: video_transcoding_start/
      Role: !GetAtt LambdaMediaConvertRole.Arn
      Environment:
        Variables:
          MEDIA_CONVERT_ROLE_ARN: !GetAtt MediaConvertS3Role.Arn
  VideoTranscodingCheckFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: video_transcoding_check/
      Role: !GetAtt LambdaMediaConvertRole.Arn
  SlotDetectionFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: slot_detection/
      Role: !GetAtt LambdaDataplaneRole.Arn
      Environment:
        Variables:
          # Silence
          START_THRESHOLD_IN_SECONDS: 3
          SILENT_THRESHOLD: -50
          # Context
          CONTEXT_MIN_CONFIDENCE: 70
          CONTEXT_INTERVAL_IN_SECONDS: 2
  VmapGenerationFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: vmap_generation/
      Role: !GetAtt LambdaDataplaneRole.Arn
      Environment:
        Variables:
          TOP_SLOTS_QTY: 3

  #############
  # Operators #
  #############
  VideoTranscodingOperator:
    Type: Custom::CustomResource
    Properties:
      ServiceToken: !Ref WorkflowCustomResourceArn
      ResourceType: "Operation"
      Name: "videoTranscoding"
      Type: "Async"
      Configuration:
          {
            "MediaType": "Video",
            "Enabled": true
          }
      StartLambdaArn: !GetAtt VideoTranscodingStartFunction.Arn
      MonitorLambdaArn: !GetAtt VideoTranscodingCheckFunction.Arn
      StateMachineExecutionRoleArn: !GetAtt StateMachineExecutionRole.Arn
  SlotDetectionOperator:
    Type: Custom::CustomResource
    Properties:
      ServiceToken: !Ref WorkflowCustomResourceArn
      ResourceType: "Operation"
      Name: "slotDetection"
      Type: "Sync"
      Configuration:
          {
            "MediaType": "Video",
            "Enabled": true
          }
      StartLambdaArn: !GetAtt SlotDetectionFunction.Arn
      StateMachineExecutionRoleArn: !GetAtt StateMachineExecutionRole.Arn
  VmapGenerationOperator:
    Type: Custom::CustomResource
    Properties:
      ServiceToken: !Ref WorkflowCustomResourceArn
      ResourceType: "Operation"
      Name: "vmapGeneration"
      Type: "Sync"
      Configuration:
          {
            "MediaType": "Video",
            "Enabled": true
          }
      StartLambdaArn: !GetAtt VmapGenerationFunction.Arn
      StateMachineExecutionRoleArn: !GetAtt StateMachineExecutionRole.Arn

  ##########
  # Stages #
  ##########
  SmartAdBreaksStage1:
    DependsOn:
      - VideoTranscodingOperator
    Type: Custom::CustomResource
    Properties:
      ServiceToken: !Ref WorkflowCustomResourceArn
      ResourceType: "Stage"
      Name: "SmartAdBreaksStage1"
      Operations:
        - !GetAtt VideoTranscodingOperator.Name
  SmartAdBreaksStage2:
    Type: Custom::CustomResource
    Properties:
      ServiceToken: !Ref WorkflowCustomResourceArn
      ResourceType: "Stage"
      Name: "SmartAdBreaksStage2"
      Operations:
        - labelDetection
        - celebrityRecognition
        - faceDetection
        - contentModeration
        - shotDetection
        - technicalCueDetection
  SmartAdBreaksStage3:
    DependsOn:
      - SlotDetectionOperator
    Type: Custom::CustomResource
    Properties:
      ServiceToken: !Ref WorkflowCustomResourceArn
      ResourceType: "Stage"
      Name: "SmartAdBreaksStage3"
      Operations:
        - !GetAtt SlotDetectionOperator.Name
  SmartAdBreaksStage4:
    DependsOn:
      - VmapGenerationOperator
    Type: Custom::CustomResource
    Properties:
      ServiceToken: !Ref WorkflowCustomResourceArn
      ResourceType: "Stage"
      Name: "SmartAdBreaksStage4"
      Operations:
        - !GetAtt VmapGenerationOperator.Name

  ############
  # Workflow #
  ############
  SmartAdBreaksWorkflow:
    DependsOn:
      - SmartAdBreaksStage1
      - SmartAdBreaksStage2
      - SmartAdBreaksStage3
      - SmartAdBreaksStage4
    Type: Custom::CustomResource
    Properties:
      ServiceToken: !Ref WorkflowCustomResourceArn
      ResourceType: "Workflow"
      Name: "SmartAdBreaksWorkflow"
      Stages: !Sub
        - |-
          {
            "${stagename1}":
            {
                "Next": "${stagename2}"
            },
            "${stagename2}":
            {
                "Next": "${stagename3}"
            },
            "${stagename3}":
            {
                "Next": "${stagename4}"
            },
            "${stagename4}":
            {
                "End": true
            }
          }
        - stagename1: !GetAtt SmartAdBreaksStage1.Name
          stagename2: !GetAtt SmartAdBreaksStage2.Name
          stagename3: !GetAtt SmartAdBreaksStage3.Name
          stagename4: !GetAtt SmartAdBreaksStage4.Name
      StartAt: !GetAtt SmartAdBreaksStage1.Name

  ###############
  # MediaTailor #
  ###############
  MediaTailorConfig:
    Type: Custom::MediaTailorConfig
    Properties:
      ServiceToken: !GetAtt MediaTailorConfigFunction.Arn
      ConfigurationName: !Sub "${AWS::StackName}-config"
      VideoContentSource: !Sub "https://${DataplaneBucket}.s3.amazonaws.com/private"
      AdDecisionServer: !Sub "https://${DataplaneBucket}.s3.amazonaws.com/private/assets/[player_params.asset_id]/vmap/ad_breaks.vmap"
  MediaTailorConfigUpdateWithCDN:
    Type: Custom::MediaTailorConfig
    Properties:
      ServiceToken: !GetAtt MediaTailorConfigFunction.Arn
      ConfigurationName: !Sub "${AWS::StackName}-config"
      VideoContentSource: !Sub "https://${CloudFrontDistribution.DomainName}"
      AdDecisionServer: !Sub "https://${CloudFrontDistribution.DomainName}/assets/[player_params.asset_id]/vmap/ad_breaks.vmap"
      CDNContentSegmentPrefix: !Sub "https://${CloudFrontDistribution.DomainName}"
      CDNAdSegmentPrefix: !Sub "https://${CloudFrontDistribution.DomainName}"
  MediaTailorConfigFunctionRole:
    Type: AWS::IAM::Role
    Properties:
      ManagedPolicyArns: 
        - arn:aws:iam::aws:policy/CloudWatchLogsFullAccess
        - arn:aws:iam::aws:policy/AWSLambdaFullAccess
      Policies:
        - PolicyName: MediaTailorAccess
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - mediatailor:PutPlaybackConfiguration
                  - mediatailor:DeletePlaybackConfiguration
                Resource: "*"
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service: 
                - lambda.amazonaws.com
            Action: sts:AssumeRole
  MediaTailorConfigFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: mediatailor/
      Role: !GetAtt MediaTailorConfigFunctionRole.Arn

  ##############
  # CloudFront #
  ##############
  CloudFrontOAI:
    Type: AWS::CloudFront::CloudFrontOriginAccessIdentity
    Properties:
      CloudFrontOriginAccessIdentityConfig:
        Comment: !Sub "access-identity-${DataplaneBucket}.s3.amazonaws.com"
  CloudFrontDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Enabled: true
        DefaultRootObject: ''
        ViewerCertificate:
          CloudFrontDefaultCertificate: true
        Origins:
          - Id: DataplaneBucket
            DomainName: !Sub "${DataplaneBucket}.s3.amazonaws.com"
            OriginPath: '/private'
            S3OriginConfig:
              OriginAccessIdentity: !Sub "origin-access-identity/cloudfront/${CloudFrontOAI}"
          - Id: MediaTailorConfig
            DomainName: !GetAtt MediaTailorConfig.HLSPlaybackDomain
            OriginPath: ''
            CustomOriginConfig:
              OriginSSLProtocols: 
                - TLSv1.2
              OriginProtocolPolicy: https-only
          - Id: MediaTailorAdSegments
            DomainName: !Sub "segments.mediatailor.${AWS::Region}.amazonaws.com"
            OriginPath: ''
            CustomOriginConfig:
              OriginSSLProtocols: 
                - TLSv1.2
              OriginProtocolPolicy: https-only
        DefaultCacheBehavior:
          TargetOriginId: MediaTailorAdSegments
          ViewerProtocolPolicy: allow-all
          ForwardedValues:
            Cookies:
              Forward: none
            QueryString: true
        CacheBehaviors:
          - TargetOriginId: MediaTailorConfig
            ViewerProtocolPolicy: allow-all
            CachePolicyId: 4135ea2d-6df8-44a3-9df3-4b5a84be39ad # Managed-CachingDisabled
            OriginRequestPolicyId: 775133bc-15f2-49f9-abea-afb2e0bf67d2 # Managed-Elemental-MediaTailor-PersonalizedManifests
            ForwardedValues:
              Cookies:
                Forward: none
              QueryString: true
            PathPattern: "/v1/*"
          - TargetOriginId: DataplaneBucket
            ViewerProtocolPolicy: allow-all
            ForwardedValues:
              Cookies:
                Forward: none
              QueryString: true
            PathPattern: "/assets/*"
  CloudFrontBucketPermission:
    Type: Custom::CloudFrontBucketPermission
    Properties:
      ServiceToken: !GetAtt CloudFrontBucketPermissionFunction.Arn
      BucketName: !Ref DataplaneBucket
      OriginAccessIdentity: !Ref CloudFrontOAI
  CloudFrontBucketPermissionFunctionRole:
    Type: AWS::IAM::Role
    Properties:
      ManagedPolicyArns: 
        - arn:aws:iam::aws:policy/CloudWatchLogsFullAccess
        - arn:aws:iam::aws:policy/AWSLambdaFullAccess
        - arn:aws:iam::aws:policy/AmazonS3FullAccess
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service: 
                - lambda.amazonaws.com
            Action: sts:AssumeRole
  CloudFrontBucketPermissionFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: cloudfront/
      Role: !GetAtt CloudFrontBucketPermissionFunctionRole.Arn

Outputs:
  InputBucket:
    Value: !Ref InputBucket
  CloudFrontDomainName:
    Value: !Sub "https://${CloudFrontDistribution.DomainName}"
  CloudFrontHLSPlaybackPrefix:
    Value: !Sub "https://${CloudFrontDistribution.DomainName}${MediaTailorConfigUpdateWithCDN.HLSPlaybackPath}"
